In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("Наша_методика_2024-2015_v4.xlsx", sheet_name="Лист1")

In [5]:
df

,Наименование,Код налогоплательщика,CAGR,"2024, Отчетный период","2024, Группа компаний","2024, Аккредитация","2024, ОКВЭД","2024, Статус","2024, Размер компании","2024, Выручка, тыс. RUB 5D",...,"2015, Отчетный период","2015, ОКВЭД","2015, Статус","2015, Размер компании","2015, Выручка, тыс. RUB 5D","2015, Выручка, тыс. RUB","2015, Динамика","2015, Ср.сп. Численность","2015, Общ. Коэфф. Года","2015, Направление по ОКВЭД"
0,"#НАШУПРАВДОМ, ООО",4.501226e+09,NaN,2024.0,NaN,NaN,63.11,Действующая,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,0.9,NaN
1,"#НОВЫЕРЕШЕНИЯ, ООО",1.901129e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,0.9,NaN
2,"#РАЗРУЛИМ, ООО",6.679127e+09,NaN,2024.0,NaN,NaN,63.99.1,Недействующая,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,0.9,NaN
3,",,АЛЬЯНС,,, ООО",4.717007e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015.0,46.51,Действующая,NaN,NaN,9.486000e+03,NaN,0,0.3,NaN
4,"‹‹АБ-МОРЕ››, ООО",3.257060e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000e+00,NaN,0,0.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201482,"ЯШМА, ООО",3.664130e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015.0,62.01,Недействующая,NaN,NaN,0.000000e+00,NaN,0,0.9,NaN
201483,"ЯШМА, ООО",7.802378e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015.0,63.11,Недействующая,NaN,NaN,0.000000e+00,NaN,2,0.9,NaN
201484,"ЯШМА, ООО",2.464213e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015.0,62.09,Недействующая,NaN,NaN,0.000000e+00,NaN,0,0.9,NaN
201485,"ЯЬЛОКО!, ООО",6.950173e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2015.0,62.09,Недействующая,NaN,NaN,1.300000e+02,NaN,2,0.9,NaN
201486,Итог,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.806432e+09,NaN,NaN,NaN,0.0

In [4]:
import re

def calculate_revenue_5d(df):
    """
    Расчет Revenue 5D для всех лет по формуле:
    <год>, Выручка, тыс. RUB 5D = <год>, Выручка, тыс. RUB * <год>, Общ. Коэфф. Года
    """
    # Найти все года из названий столбцов
    years = set()
    for col in df.columns:
        match = re.search(r'(\d{4}),', col)
        if match:
            years.add(match.group(1))
    
    years = sorted(list(years))
    print(f"Найдены года: {years}\n")
    
    # Для каждого года рассчитать Revenue 5D
    for year in years:
        revenue_col = f"{year}, Выручка, тыс. RUB"
        coeff_col = f"{year},  Общ. Коэфф. Года"
        revenue_5d_col = f"{year}, Выручка, тыс. RUB 5D"
        
        # Проверить наличие необходимых столбцов
        if revenue_col not in df.columns:
            print(f"⚠️ Пропускаю {year}, отсутствует столбец: {revenue_col}")
            continue
        if coeff_col not in df.columns:
            print(f"⚠️ Пропускаю {year}, отсутствует столбец: {coeff_col}")
            continue
        
        # Если столбца Revenue 5D еще нет, создать его
        if revenue_5d_col not in df.columns:
            df[revenue_5d_col] = None
        
        # Рассчитать Revenue 5D для каждой строки
        for idx in df.index:
            revenue = pd.to_numeric(df.loc[idx, revenue_col], errors='coerce')
            coeff = pd.to_numeric(df.loc[idx, coeff_col], errors='coerce')
            
            # Если оба значения есть, рассчитать произведение
            if pd.notna(revenue) and pd.notna(coeff):
                df.loc[idx, revenue_5d_col] = revenue * coeff
            else:
                df.loc[idx, revenue_5d_col] = None
        
        print(f"✓ {year}, Выручка, тыс. RUB 5D рассчитан")
    
    print("\n✓ Расчет Revenue 5D завершен для всех лет!")
    return df

# Выполнить расчет
df = calculate_revenue_5d(df)

Найдены года: ['2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

✓ 2015, Выручка, тыс. RUB 5D рассчитан
✓ 2015, Выручка, тыс. RUB 5D рассчитан
✓ 2016, Выручка, тыс. RUB 5D рассчитан
✓ 2016, Выручка, тыс. RUB 5D рассчитан
✓ 2017, Выручка, тыс. RUB 5D рассчитан
✓ 2017, Выручка, тыс. RUB 5D рассчитан
✓ 2018, Выручка, тыс. RUB 5D рассчитан
✓ 2018, Выручка, тыс. RUB 5D рассчитан
✓ 2019, Выручка, тыс. RUB 5D рассчитан
✓ 2019, Выручка, тыс. RUB 5D рассчитан
✓ 2020, Выручка, тыс. RUB 5D рассчитан
✓ 2020, Выручка, тыс. RUB 5D рассчитан
✓ 2021, Выручка, тыс. RUB 5D рассчитан
✓ 2021, Выручка, тыс. RUB 5D рассчитан
✓ 2022, Выручка, тыс. RUB 5D рассчитан
✓ 2022, Выручка, тыс. RUB 5D рассчитан
✓ 2023, Выручка, тыс. RUB 5D рассчитан
✓ 2023, Выручка, тыс. RUB 5D рассчитан
✓ 2024, Выручка, тыс. RUB 5D рассчитан

✓ Расчет Revenue 5D завершен для всех лет!
✓ 2024, Выручка, тыс. RUB 5D рассчитан

✓ Расчет Revenue 5D завершен для всех лет!

In [10]:
def classify_company_size_all_years(df):
    """
    Заполняет столбцы "<год>, Размер компании" по значениям
    "<год>, Выручка, тыс. RUB 5D". Значения в столбце — в тысячах.

    Категории (в тыс.):
    - >= 5_000_000 : 'Крупнейшее предприятие'
    - >= 2_000_000 : 'Крупное предприятие'
    - >= 1_000_000 : 'Средне-крупное предприятие'
    - >=   500_000 : 'Среднее предприятие'
    - >=   100_000 : 'Малое предприятие'
    - <    100_000 : 'Микропредприятие'
    """
    years = set()
    for col in df.columns:
        m = re.search(r"(\d{4}),", col)
        if m:
            years.add(m.group(1))
    years = sorted(years)

    thresholds = [
        (5_000_000, 'Крупнейшее предприятие'),
        (2_000_000, 'Крупное предприятие'),
        (1_000_000, 'Средне-крупное предприятие'),
        (500_000, 'Среднее предприятие'),
        (100_000, 'Малое предприятие'),
        (0, 'Микропредприятие'),
    ]

    for year in years:
        rev5d_col = f"{year}, Выручка, тыс. RUB 5D"
        size_col = f"{year}, Размер компании"

        if rev5d_col not in df.columns:
            print(f"⚠️ Пропускаю {year}, отсутствует столбец: {rev5d_col}")
            continue

        # Инициализируем колонку (строго object dtype для смешанных значений)
        df[size_col] = pd.Series([None] * len(df), dtype="object")

        # Конвертация в числовой формат (тысячи)
        vals = pd.to_numeric(df[rev5d_col], errors='coerce')

        # Присваиваем метки
        labels = []
        for v in vals:
            if pd.isna(v):
                labels.append(None)
                continue
            assigned = None
            for thr, label in thresholds:
                if v >= thr:
                    assigned = label
                    break
            labels.append(assigned)

        df[size_col] = labels
        print(f"✓ {year}, Размер компании заполнен")

    print("\n✓ Классификация по размерам для всех годов завершена")
    return df

# Выполнить классификацию
df = classify_company_size_all_years(df)

✓ 2015, Размер компании заполнен
✓ 2016, Размер компании заполнен
✓ 2017, Размер компании заполнен
✓ 2018, Размер компании заполнен
✓ 2019, Размер компании заполнен
✓ 2020, Размер компании заполнен
✓ 2021, Размер компании заполнен
✓ 2018, Размер компании заполнен
✓ 2019, Размер компании заполнен
✓ 2020, Размер компании заполнен
✓ 2021, Размер компании заполнен
✓ 2022, Размер компании заполнен
✓ 2023, Размер компании заполнен
✓ 2024, Размер компании заполнен

✓ Классификация по размерам для всех годов завершена
✓ 2022, Размер компании заполнен
✓ 2023, Размер компании заполнен
✓ 2024, Размер компании заполнен

✓ Классификация по размерам для всех годов завершена

In [8]:
def calculate_dynamics(df):
    """
    Расчет динамики (YoY) для каждого года по формуле:
    <год>, Динамика = (<год>, Выручка, тыс. RUB 5D - <год-1>, Выручка, тыс. RUB 5D) / <год-1>, Выручка, тыс. RUB 5D
    
    Если одно из значений = 0, то пишем "Выручка равна 0"
    """
    # Найти все года из названий столбцов
    years = set()
    for col in df.columns:
        match = re.search(r'(\d{4}),', col)
        if match:
            years.add(int(match.group(1)))
    
    years = sorted(list(years))
    print(f"Найдены года: {years}\n")
    
    # Для каждого года (начиная со второго года) рассчитать динамику
    for i in range(1, len(years)):
        current_year = years[i]
        prev_year = years[i-1]
        
        current_revenue_5d_col = f"{current_year}, Выручка, тыс. RUB 5D"
        prev_revenue_5d_col = f"{prev_year}, Выручка, тыс. RUB 5D"
        dynamics_col = f"{current_year}, Динамика"
        
        # Проверить наличие необходимых столбцов
        if current_revenue_5d_col not in df.columns:
            print(f"⚠️ Пропускаю {current_year}, отсутствует столбец: {current_revenue_5d_col}")
            continue
        if prev_revenue_5d_col not in df.columns:
            print(f"⚠️ Пропускаю {current_year}, отсутствует столбец: {prev_revenue_5d_col}")
            continue
        
        # Если столбца динамики еще нет, создать его
        if dynamics_col not in df.columns:
            df[dynamics_col] = None
        
        # Рассчитать динамику для каждой строки
        for idx in df.index:
            current_val = pd.to_numeric(df.loc[idx, current_revenue_5d_col], errors='coerce')
            prev_val = pd.to_numeric(df.loc[idx, prev_revenue_5d_col], errors='coerce')
            
            # Если одно из значений равно 0 или оба значения отсутствуют
            if (pd.notna(current_val) and current_val == 0) or (pd.notna(prev_val) and prev_val == 0):
                df.loc[idx, dynamics_col] = "Выручка равна 0"
            # Если оба значения есть и не равны нулю, рассчитать динамику
            elif pd.notna(current_val) and pd.notna(prev_val) and prev_val != 0:
                df.loc[idx, dynamics_col] = (current_val - prev_val) / prev_val
            else:
                df.loc[idx, dynamics_col] = None
        
        print(f"✓ {current_year}, Динамика рассчитана")
    
    print("\n✓ Расчет динамики завершен для всех лет!")
    print("⚠️ Примечание: если выручка = 0, показано 'Выручка равна 0'")
    return df

# Выполнить расчет
df = calculate_dynamics(df)

Найдены года: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2016, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2017, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2018, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2019, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2020, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2021, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2022, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2023, Динамика рассчитана

/var/folders/g1/63nyb55d7r16b0nhyqd64gkh0000gn/T/ipykernel_18967/4278010231.py:46: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Выручка равна 0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[idx, dynamics_col] = "Выручка равна 0"

✓ 2024, Динамика рассчитана

✓ Расчет динамики завершен для всех лет!
⚠️ Примечание: если выручка = 0, показано 'Выручка равна 0'

In [11]:
df

,Наименование,Код налогоплательщика,CAGR,"2024, Отчетный период","2024, Группа компаний","2024, Аккредитация","2024, ОКВЭД","2024, Статус","2024, Размер компании","2024, Выручка, тыс. RUB 5D",...,"2015, Отчетный период","2015, ОКВЭД","2015, Статус","2015, Размер компании","2015, Выручка, тыс. RUB 5D","2015, Выручка, тыс. RUB","2015, Динамика","2015, Ср.сп. Численность","2015, Общ. Коэфф. Года","2015, Направление по ОКВЭД"
0,"#НАШУПРАВДОМ, ООО",4.501226e+09,NaN,2024.0,NaN,NaN,63.11,Действующая,Микропредприятие,5047.2,...,NaN,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN
1,"#НОВЫЕРЕШЕНИЯ, ООО",1.901129e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,NaN,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN
2,"#РАЗРУЛИМ, ООО",6.679127e+09,NaN,2024.0,NaN,NaN,63.99.1,Недействующая,Микропредприятие,0.0,...,NaN,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN
3,",,АЛЬЯНС,,, ООО",4.717007e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,2015.0,46.51,Действующая,Микропредприятие,2845.8,9.486000e+03,NaN,0,0.3,NaN
4,"‹‹АБ-МОРЕ››, ООО",3.257060e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,NaN,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201482,"ЯШМА, ООО",3.664130e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,2015.0,62.01,Недействующая,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN
201483,"ЯШМА, ООО",7.802378e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,2015.0,63.11,Недействующая,Микропредприятие,0.0,0.000000e+00,NaN,2,0.9,NaN
201484,"ЯШМА, ООО",2.464213e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,2015.0,62.09,Недействующая,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN
201485,"ЯЬЛОКО!, ООО",6.950173e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,2015.0,62.09,Недействующая,Микропредприятие,117.0,1.300000e+02,NaN,2,0.9,NaN
201486,Итог,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,NaN,None,NaN,3.806432e+09,NaN,NaN,NaN,0.0

In [12]:
def calculate_cagr_with_years(df, min_periods=2):
    """
    Рассчитать CAGR по каждой компании, используя только крайние существующие годы с положительной выручкой (в тыс.).

    Правила:
    - Берём только года, где '<год>, Выручка, тыс. RUB 5D' > 0.
    - Вычисляем первый и последний год с данными: first_year, last_year.
    - periods = last_year - first_year
    - Если periods < min_periods -> не считаем (оставляем пусто)
    - Иначе: CAGR = (last_value / first_value) ** (1/periods) - 1
    - Добавляем два столбца: 'CAGR' (float) и 'CAGR Годы' (строка вида '2015-2024 (9)')
    """
    # Найти доступные годы по шаблону
    years = []
    pattern = re.compile(r"(\d{4}), Выручка, тыс. RUB 5D")
    for col in df.columns:
        m = pattern.search(col)
        if m:
            years.append(int(m.group(1)))
    years = sorted(set(years))
    if not years:
        print("Не найдено столбцов 'Выручка, тыс. RUB 5D'.")
        return df

    # Инициализация столбцов
    df['CAGR'] = pd.Series([None] * len(df), dtype='float64')
    df['CAGR Годы'] = pd.Series([None] * len(df), dtype='object')

    # Для каждой строки определяем первый и последний год с положительной выручкой
    for idx in df.index:
        years_with_values = []
        values = {}
        for y in years:
            col = f"{y}, Выручка, тыс. RUB 5D"
            if col in df.columns:
                val = pd.to_numeric(df.at[idx, col], errors='coerce')
                if pd.notna(val) and val > 0:
                    years_with_values.append(y)
                    values[y] = val

        if len(years_with_values) < 2:
            # недостаточно данных
            continue

        first_year = min(years_with_values)
        last_year = max(years_with_values)
        periods = last_year - first_year

        if periods < min_periods:
            # не считаем, слишком короткий промежуток (например, соседние годы)
            continue

        first_val = values.get(first_year)
        last_val = values.get(last_year)

        if first_val is None or last_val is None or first_val <= 0:
            continue

        try:
            cagr = (last_val / first_val) ** (1.0 / periods) - 1.0
        except Exception:
            cagr = None

        df.at[idx, 'CAGR'] = cagr
        df.at[idx, 'CAGR Годы'] = f"{first_year}-{last_year} ({periods})"

    print(f"✓ CAGR рассчитан (минимум period = {min_periods}) для компаний с достаточными данными")
    return df

# Выполнить расчёт CAGR (минимум 2 промежутка -> период >=2)
df = calculate_cagr_with_years(df, min_periods=2)

✓ CAGR рассчитан (минимум period = 2) для компаний с достаточными данными

In [13]:
df

,Наименование,Код налогоплательщика,CAGR,"2024, Отчетный период","2024, Группа компаний","2024, Аккредитация","2024, ОКВЭД","2024, Статус","2024, Размер компании","2024, Выручка, тыс. RUB 5D",...,"2015, ОКВЭД","2015, Статус","2015, Размер компании","2015, Выручка, тыс. RUB 5D","2015, Выручка, тыс. RUB","2015, Динамика","2015, Ср.сп. Численность","2015, Общ. Коэфф. Года","2015, Направление по ОКВЭД",CAGR Годы
0,"#НАШУПРАВДОМ, ООО",4.501226e+09,0.464239,2024.0,NaN,NaN,63.11,Действующая,Микропредприятие,5047.2,...,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN,2020-2024 (4)
1,"#НОВЫЕРЕШЕНИЯ, ООО",1.901129e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN,None
2,"#РАЗРУЛИМ, ООО",6.679127e+09,NaN,2024.0,NaN,NaN,63.99.1,Недействующая,Микропредприятие,0.0,...,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN,None
3,",,АЛЬЯНС,,, ООО",4.717007e+09,-0.057730,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,46.51,Действующая,Микропредприятие,2845.8,9.486000e+03,NaN,0,0.3,NaN,2015-2019 (4)
4,"‹‹АБ-МОРЕ››, ООО",3.257060e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,NaN,NaN,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201482,"ЯШМА, ООО",3.664130e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,62.01,Недействующая,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN,None
201483,"ЯШМА, ООО",7.802378e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,63.11,Недействующая,Микропредприятие,0.0,0.000000e+00,NaN,2,0.9,NaN,None
201484,"ЯШМА, ООО",2.464213e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,62.09,Недействующая,Микропредприятие,0.0,0.000000e+00,NaN,0,0.9,NaN,None
201485,"ЯЬЛОКО!, ООО",6.950173e+09,NaN,NaN,NaN,NaN,NaN,NaN,Микропредприятие,0.0,...,62.09,Недействующая,Микропредприятие,117.0,1.300000e+02,NaN,2,0.9,NaN,None
201486,Итог,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,...,NaN,NaN,None,NaN,3.806432e+09,NaN,NaN,NaN,0.0,None

In [ ]:
output_path = "Готовое решение_main2.xlsx"
try:
    df.to_excel(output_path, index=False)
    print(f"Файл сохранён: {output_path}")
    print(f"Строк: {len(df)}, столбцов: {len(df.columns)}")
except Exception as e:
    print("Ошибка при сохранении:", e)